SELECT CONCAT(cr.ITEM, cr.ITEM1, cr.ITEM2, cr.ITEM3, cr.ITEM4, cr.ITEM5) AS crypt
FROM (
    SELECT ASCII(SUBSTRING('REGICE', 1, 1)) AS ITEM,
       ASCII(SUBSTRING('REGICE', 2, 1)) AS ITEM1,
       ASCII(SUBSTRING('REGICE', 3, 1)) AS ITEM2,
       ASCII(SUBSTRING('REGICE', 4, 1)) AS ITEM3,
       ASCII(SUBSTRING('REGICE', 5, 1)) AS ITEM4,
       ASCII(SUBSTRING('REGICE', 6, 1)) AS ITEM5
) AS cr;